# Cricket Players Data - 100 Greatest ODI Players Post-1980
# All stats are based on historical ODI career data

PLAYERS_DATA = [
    # ============ BATTERS ============
    # India
    {"id": "sachin_tendulkar", "name": "Sachin Tendulkar", "country": "India", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 44.83, "strike_rate": 86.23, "powerplay_sr": 75, "middle_sr": 85, "death_sr": 95, "vs_pace": 0.85, "vs_spin": 0.90, "pressure_factor": 0.95}, "bowling": {"economy": 5.10, "wickets_per_over": 0.05, "dot_ball_pct": 0.30}, "era": "1989-2012"},
    {"id": "virat_kohli", "name": "Virat Kohli", "country": "India", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 58.18, "strike_rate": 93.25, "powerplay_sr": 80, "middle_sr": 92, "death_sr": 105, "vs_pace": 0.88, "vs_spin": 0.92, "pressure_factor": 0.97}, "bowling": {"economy": 6.50, "wickets_per_over": 0.02, "dot_ball_pct": 0.20}, "era": "2008-present"},
    {"id": "rohit_sharma", "name": "Rohit Sharma", "country": "India", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 49.42, "strike_rate": 91.17, "powerplay_sr": 95, "middle_sr": 88, "death_sr": 100, "vs_pace": 0.85, "vs_spin": 0.88, "pressure_factor": 0.90}, "bowling": {"economy": 5.80, "wickets_per_over": 0.03, "dot_ball_pct": 0.25}, "era": "2007-present"},
    {"id": "ms_dhoni", "name": "MS Dhoni", "country": "India", "role": "Wicketkeeper-Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 50.57, "strike_rate": 87.56, "powerplay_sr": 70, "middle_sr": 82, "death_sr": 115, "vs_pace": 0.82, "vs_spin": 0.88, "pressure_factor": 0.98}, "bowling": {"economy": 0, "wickets_per_over": 0, "dot_ball_pct": 0}, "era": "2004-2019"},
    {"id": "sourav_ganguly", "name": "Sourav Ganguly", "country": "India", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm medium", "batting": {"average": 41.02, "strike_rate": 73.70, "powerplay_sr": 78, "middle_sr": 72, "death_sr": 80, "vs_pace": 0.80, "vs_spin": 0.85, "pressure_factor": 0.88}, "bowling": {"economy": 5.67, "wickets_per_over": 0.05, "dot_ball_pct": 0.28}, "era": "1992-2007"},
    {"id": "rahul_dravid", "name": "Rahul Dravid", "country": "India", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 39.16, "strike_rate": 71.22, "powerplay_sr": 65, "middle_sr": 72, "death_sr": 78, "vs_pace": 0.88, "vs_spin": 0.85, "pressure_factor": 0.92}, "bowling": {"economy": 6.00, "wickets_per_over": 0.01, "dot_ball_pct": 0.22}, "era": "1996-2011"},
    {"id": "yuvraj_singh", "name": "Yuvraj Singh", "country": "India", "role": "All-rounder", "batting_style": "Left-handed", "bowling_style": "Left-arm orthodox", "batting": {"average": 36.55, "strike_rate": 87.64, "powerplay_sr": 82, "middle_sr": 88, "death_sr": 105, "vs_pace": 0.82, "vs_spin": 0.80, "pressure_factor": 0.88}, "bowling": {"economy": 5.02, "wickets_per_over": 0.06, "dot_ball_pct": 0.35}, "era": "2000-2017"},
    {"id": "shikhar_dhawan", "name": "Shikhar Dhawan", "country": "India", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm off break", "batting": {"average": 44.59, "strike_rate": 92.00, "powerplay_sr": 98, "middle_sr": 88, "death_sr": 95, "vs_pace": 0.85, "vs_spin": 0.82, "pressure_factor": 0.85}, "bowling": {"economy": 7.00, "wickets_per_over": 0.01, "dot_ball_pct": 0.18}, "era": "2010-present"},
    {"id": "vvs_laxman", "name": "VVS Laxman", "country": "India", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 30.76, "strike_rate": 70.34, "powerplay_sr": 62, "middle_sr": 72, "death_sr": 78, "vs_pace": 0.82, "vs_spin": 0.85, "pressure_factor": 0.85}, "bowling": {"economy": 6.50, "wickets_per_over": 0.01, "dot_ball_pct": 0.20}, "era": "1996-2006"},
    
    # Australia
    {"id": "ricky_ponting", "name": "Ricky Ponting", "country": "Australia", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 42.03, "strike_rate": 80.39, "powerplay_sr": 75, "middle_sr": 80, "death_sr": 90, "vs_pace": 0.88, "vs_spin": 0.85, "pressure_factor": 0.92}, "bowling": {"economy": 6.20, "wickets_per_over": 0.01, "dot_ball_pct": 0.20}, "era": "1995-2012"},
    {"id": "adam_gilchrist", "name": "Adam Gilchrist", "country": "Australia", "role": "Wicketkeeper-Batsman", "batting_style": "Left-handed", "bowling_style": "None", "batting": {"average": 35.89, "strike_rate": 96.94, "powerplay_sr": 105, "middle_sr": 95, "death_sr": 100, "vs_pace": 0.85, "vs_spin": 0.82, "pressure_factor": 0.88}, "bowling": {"economy": 0, "wickets_per_over": 0, "dot_ball_pct": 0}, "era": "1996-2008"},
    {"id": "matthew_hayden", "name": "Matthew Hayden", "country": "Australia", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm medium", "batting": {"average": 43.80, "strike_rate": 78.96, "powerplay_sr": 85, "middle_sr": 78, "death_sr": 82, "vs_pace": 0.85, "vs_spin": 0.80, "pressure_factor": 0.88}, "bowling": {"economy": 7.00, "wickets_per_over": 0.01, "dot_ball_pct": 0.18}, "era": "1993-2008"},
    {"id": "steve_waugh", "name": "Steve Waugh", "country": "Australia", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 32.90, "strike_rate": 75.91, "powerplay_sr": 68, "middle_sr": 75, "death_sr": 85, "vs_pace": 0.82, "vs_spin": 0.85, "pressure_factor": 0.95}, "bowling": {"economy": 4.76, "wickets_per_over": 0.05, "dot_ball_pct": 0.35}, "era": "1986-2004"},
    {"id": "mark_waugh", "name": "Mark Waugh", "country": "Australia", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 39.35, "strike_rate": 76.90, "powerplay_sr": 72, "middle_sr": 78, "death_sr": 82, "vs_pace": 0.85, "vs_spin": 0.88, "pressure_factor": 0.85}, "bowling": {"economy": 5.15, "wickets_per_over": 0.04, "dot_ball_pct": 0.30}, "era": "1988-2002"},
    {"id": "michael_clarke", "name": "Michael Clarke", "country": "Australia", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Left-arm orthodox", "batting": {"average": 44.58, "strike_rate": 78.38, "powerplay_sr": 70, "middle_sr": 78, "death_sr": 88, "vs_pace": 0.85, "vs_spin": 0.88, "pressure_factor": 0.90}, "bowling": {"economy": 5.31, "wickets_per_over": 0.04, "dot_ball_pct": 0.32}, "era": "2003-2015"},
    {"id": "david_warner", "name": "David Warner", "country": "Australia", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 45.30, "strike_rate": 97.03, "powerplay_sr": 105, "middle_sr": 95, "death_sr": 98, "vs_pace": 0.88, "vs_spin": 0.82, "pressure_factor": 0.85}, "bowling": {"economy": 7.50, "wickets_per_over": 0.01, "dot_ball_pct": 0.15}, "era": "2009-present"},
    {"id": "steve_smith", "name": "Steve Smith", "country": "Australia", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 43.67, "strike_rate": 87.43, "powerplay_sr": 75, "middle_sr": 88, "death_sr": 95, "vs_pace": 0.90, "vs_spin": 0.88, "pressure_factor": 0.92}, "bowling": {"economy": 5.80, "wickets_per_over": 0.03, "dot_ball_pct": 0.28}, "era": "2010-present"},
    {"id": "dean_jones", "name": "Dean Jones", "country": "Australia", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 44.61, "strike_rate": 72.56, "powerplay_sr": 68, "middle_sr": 72, "death_sr": 80, "vs_pace": 0.82, "vs_spin": 0.85, "pressure_factor": 0.88}, "bowling": {"economy": 5.50, "wickets_per_over": 0.02, "dot_ball_pct": 0.28}, "era": "1984-1994"},
    
    # England
    {"id": "joe_root", "name": "Joe Root", "country": "England", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 51.07, "strike_rate": 87.20, "powerplay_sr": 72, "middle_sr": 88, "death_sr": 95, "vs_pace": 0.88, "vs_spin": 0.90, "pressure_factor": 0.90}, "bowling": {"economy": 5.32, "wickets_per_over": 0.04, "dot_ball_pct": 0.30}, "era": "2013-present"},
    {"id": "kevin_pietersen", "name": "Kevin Pietersen", "country": "England", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 40.73, "strike_rate": 86.58, "powerplay_sr": 78, "middle_sr": 88, "death_sr": 98, "vs_pace": 0.85, "vs_spin": 0.82, "pressure_factor": 0.88}, "bowling": {"economy": 5.45, "wickets_per_over": 0.03, "dot_ball_pct": 0.28}, "era": "2004-2014"},
    {"id": "eoin_morgan", "name": "Eoin Morgan", "country": "England", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm medium", "batting": {"average": 39.20, "strike_rate": 91.05, "powerplay_sr": 78, "middle_sr": 90, "death_sr": 110, "vs_pace": 0.85, "vs_spin": 0.88, "pressure_factor": 0.92}, "bowling": {"economy": 6.00, "wickets_per_over": 0.01, "dot_ball_pct": 0.20}, "era": "2006-2022"},
    {"id": "jos_buttler", "name": "Jos Buttler", "country": "England", "role": "Wicketkeeper-Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 40.78, "strike_rate": 118.91, "powerplay_sr": 95, "middle_sr": 115, "death_sr": 145, "vs_pace": 0.88, "vs_spin": 0.85, "pressure_factor": 0.88}, "bowling": {"economy": 0, "wickets_per_over": 0, "dot_ball_pct": 0}, "era": "2012-present"},
    {"id": "ben_stokes", "name": "Ben Stokes", "country": "England", "role": "All-rounder", "batting_style": "Left-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 38.98, "strike_rate": 95.11, "powerplay_sr": 85, "middle_sr": 92, "death_sr": 120, "vs_pace": 0.85, "vs_spin": 0.82, "pressure_factor": 0.95}, "bowling": {"economy": 6.15, "wickets_per_over": 0.06, "dot_ball_pct": 0.32}, "era": "2011-present"},
    {"id": "jonny_bairstow", "name": "Jonny Bairstow", "country": "England", "role": "Wicketkeeper-Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 46.91, "strike_rate": 103.89, "powerplay_sr": 95, "middle_sr": 102, "death_sr": 118, "vs_pace": 0.85, "vs_spin": 0.82, "pressure_factor": 0.85}, "bowling": {"economy": 0, "wickets_per_over": 0, "dot_ball_pct": 0}, "era": "2011-present"},
    {"id": "graham_gooch", "name": "Graham Gooch", "country": "England", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 36.98, "strike_rate": 61.17, "powerplay_sr": 58, "middle_sr": 62, "death_sr": 68, "vs_pace": 0.82, "vs_spin": 0.85, "pressure_factor": 0.88}, "bowling": {"economy": 5.20, "wickets_per_over": 0.03, "dot_ball_pct": 0.30}, "era": "1976-1995"},
    
    # South Africa
    {"id": "ab_devilliers", "name": "AB de Villiers", "country": "South Africa", "role": "Wicketkeeper-Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 53.50, "strike_rate": 101.09, "powerplay_sr": 90, "middle_sr": 100, "death_sr": 135, "vs_pace": 0.92, "vs_spin": 0.90, "pressure_factor": 0.95}, "bowling": {"economy": 0, "wickets_per_over": 0, "dot_ball_pct": 0}, "era": "2005-2018"},
    {"id": "hashim_amla", "name": "Hashim Amla", "country": "South Africa", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 49.46, "strike_rate": 88.39, "powerplay_sr": 78, "middle_sr": 90, "death_sr": 95, "vs_pace": 0.90, "vs_spin": 0.88, "pressure_factor": 0.90}, "bowling": {"economy": 6.50, "wickets_per_over": 0.01, "dot_ball_pct": 0.18}, "era": "2008-2019"},
    {"id": "jacques_kallis", "name": "Jacques Kallis", "country": "South Africa", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 44.36, "strike_rate": 72.89, "powerplay_sr": 65, "middle_sr": 72, "death_sr": 85, "vs_pace": 0.88, "vs_spin": 0.90, "pressure_factor": 0.92}, "bowling": {"economy": 4.84, "wickets_per_over": 0.06, "dot_ball_pct": 0.38}, "era": "1996-2014"},
    {"id": "graeme_smith", "name": "Graeme Smith", "country": "South Africa", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm off break", "batting": {"average": 37.98, "strike_rate": 80.93, "powerplay_sr": 85, "middle_sr": 78, "death_sr": 85, "vs_pace": 0.82, "vs_spin": 0.85, "pressure_factor": 0.88}, "bowling": {"economy": 6.00, "wickets_per_over": 0.01, "dot_ball_pct": 0.20}, "era": "2002-2014"},
    {"id": "herschelle_gibbs", "name": "Herschelle Gibbs", "country": "South Africa", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 36.13, "strike_rate": 83.26, "powerplay_sr": 90, "middle_sr": 82, "death_sr": 85, "vs_pace": 0.82, "vs_spin": 0.80, "pressure_factor": 0.78}, "bowling": {"economy": 5.50, "wickets_per_over": 0.02, "dot_ball_pct": 0.25}, "era": "1996-2010"},
    {"id": "quinton_dekock", "name": "Quinton de Kock", "country": "South Africa", "role": "Wicketkeeper-Batsman", "batting_style": "Left-handed", "bowling_style": "None", "batting": {"average": 44.86, "strike_rate": 96.04, "powerplay_sr": 105, "middle_sr": 92, "death_sr": 100, "vs_pace": 0.88, "vs_spin": 0.82, "pressure_factor": 0.85}, "bowling": {"economy": 0, "wickets_per_over": 0, "dot_ball_pct": 0}, "era": "2013-present"},
    {"id": "faf_duplessis", "name": "Faf du Plessis", "country": "South Africa", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 47.43, "strike_rate": 88.30, "powerplay_sr": 78, "middle_sr": 88, "death_sr": 102, "vs_pace": 0.85, "vs_spin": 0.88, "pressure_factor": 0.90}, "bowling": {"economy": 6.00, "wickets_per_over": 0.01, "dot_ball_pct": 0.20}, "era": "2011-2023"},
    {"id": "jonty_rhodes", "name": "Jonty Rhodes", "country": "South Africa", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 35.66, "strike_rate": 80.91, "powerplay_sr": 75, "middle_sr": 80, "death_sr": 92, "vs_pace": 0.82, "vs_spin": 0.85, "pressure_factor": 0.85}, "bowling": {"economy": 6.20, "wickets_per_over": 0.02, "dot_ball_pct": 0.22}, "era": "1992-2003"},
    
    # West Indies
    {"id": "vivian_richards", "name": "Vivian Richards", "country": "West Indies", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 47.00, "strike_rate": 90.20, "powerplay_sr": 88, "middle_sr": 90, "death_sr": 98, "vs_pace": 0.92, "vs_spin": 0.88, "pressure_factor": 0.95}, "bowling": {"economy": 5.35, "wickets_per_over": 0.04, "dot_ball_pct": 0.30}, "era": "1975-1991"},
    {"id": "brian_lara", "name": "Brian Lara", "country": "West Indies", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 40.48, "strike_rate": 79.51, "powerplay_sr": 75, "middle_sr": 80, "death_sr": 88, "vs_pace": 0.88, "vs_spin": 0.90, "pressure_factor": 0.90}, "bowling": {"economy": 6.50, "wickets_per_over": 0.01, "dot_ball_pct": 0.18}, "era": "1990-2007"},
    {"id": "chris_gayle", "name": "Chris Gayle", "country": "West Indies", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm off break", "batting": {"average": 37.83, "strike_rate": 85.84, "powerplay_sr": 100, "middle_sr": 82, "death_sr": 90, "vs_pace": 0.85, "vs_spin": 0.80, "pressure_factor": 0.82}, "bowling": {"economy": 5.04, "wickets_per_over": 0.04, "dot_ball_pct": 0.32}, "era": "1999-2019"},
    {"id": "desmond_haynes", "name": "Desmond Haynes", "country": "West Indies", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 41.37, "strike_rate": 65.47, "powerplay_sr": 62, "middle_sr": 65, "death_sr": 72, "vs_pace": 0.85, "vs_spin": 0.88, "pressure_factor": 0.90}, "bowling": {"economy": 5.80, "wickets_per_over": 0.01, "dot_ball_pct": 0.25}, "era": "1978-1994"},
    {"id": "gordon_greenidge", "name": "Gordon Greenidge", "country": "West Indies", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 45.03, "strike_rate": 63.90, "powerplay_sr": 60, "middle_sr": 65, "death_sr": 70, "vs_pace": 0.88, "vs_spin": 0.85, "pressure_factor": 0.88}, "bowling": {"economy": 6.00, "wickets_per_over": 0.01, "dot_ball_pct": 0.22}, "era": "1975-1991"},
    {"id": "clive_lloyd", "name": "Clive Lloyd", "country": "West Indies", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm medium", "batting": {"average": 39.54, "strike_rate": 77.20, "powerplay_sr": 72, "middle_sr": 78, "death_sr": 85, "vs_pace": 0.85, "vs_spin": 0.82, "pressure_factor": 0.92}, "bowling": {"economy": 5.50, "wickets_per_over": 0.02, "dot_ball_pct": 0.28}, "era": "1975-1985"},
    {"id": "shivnarine_chanderpaul", "name": "Shivnarine Chanderpaul", "country": "West Indies", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 41.60, "strike_rate": 70.71, "powerplay_sr": 62, "middle_sr": 70, "death_sr": 82, "vs_pace": 0.85, "vs_spin": 0.88, "pressure_factor": 0.90}, "bowling": {"economy": 5.75, "wickets_per_over": 0.02, "dot_ball_pct": 0.28}, "era": "1994-2011"},
    
    # Pakistan
    {"id": "javed_miandad", "name": "Javed Miandad", "country": "Pakistan", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 41.70, "strike_rate": 67.00, "powerplay_sr": 60, "middle_sr": 68, "death_sr": 75, "vs_pace": 0.88, "vs_spin": 0.92, "pressure_factor": 0.95}, "bowling": {"economy": 5.50, "wickets_per_over": 0.02, "dot_ball_pct": 0.28}, "era": "1975-1996"},
    {"id": "babar_azam", "name": "Babar Azam", "country": "Pakistan", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 56.92, "strike_rate": 88.89, "powerplay_sr": 78, "middle_sr": 90, "death_sr": 98, "vs_pace": 0.90, "vs_spin": 0.88, "pressure_factor": 0.90}, "bowling": {"economy": 6.50, "wickets_per_over": 0.01, "dot_ball_pct": 0.18}, "era": "2015-present"},
    {"id": "inzamam_ul_haq", "name": "Inzamam-ul-Haq", "country": "Pakistan", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 39.52, "strike_rate": 74.24, "powerplay_sr": 68, "middle_sr": 75, "death_sr": 82, "vs_pace": 0.85, "vs_spin": 0.88, "pressure_factor": 0.85}, "bowling": {"economy": 6.00, "wickets_per_over": 0.01, "dot_ball_pct": 0.20}, "era": "1991-2007"},
    {"id": "mohammad_yousuf", "name": "Mohammad Yousuf", "country": "Pakistan", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 41.71, "strike_rate": 74.64, "powerplay_sr": 68, "middle_sr": 75, "death_sr": 82, "vs_pace": 0.85, "vs_spin": 0.90, "pressure_factor": 0.88}, "bowling": {"economy": 6.20, "wickets_per_over": 0.01, "dot_ball_pct": 0.20}, "era": "1998-2010"},
    {"id": "saeed_anwar", "name": "Saeed Anwar", "country": "Pakistan", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm off break", "batting": {"average": 39.21, "strike_rate": 80.67, "powerplay_sr": 85, "middle_sr": 80, "death_sr": 82, "vs_pace": 0.85, "vs_spin": 0.82, "pressure_factor": 0.85}, "bowling": {"economy": 6.00, "wickets_per_over": 0.01, "dot_ball_pct": 0.20}, "era": "1989-2003"},
    {"id": "zaheer_abbas", "name": "Zaheer Abbas", "country": "Pakistan", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 47.62, "strike_rate": 84.75, "powerplay_sr": 78, "middle_sr": 85, "death_sr": 92, "vs_pace": 0.82, "vs_spin": 0.88, "pressure_factor": 0.85}, "bowling": {"economy": 6.50, "wickets_per_over": 0.01, "dot_ball_pct": 0.18}, "era": "1974-1985"},
    
    # Sri Lanka
    {"id": "sanath_jayasuriya", "name": "Sanath Jayasuriya", "country": "Sri Lanka", "role": "All-rounder", "batting_style": "Left-handed", "bowling_style": "Left-arm orthodox", "batting": {"average": 32.36, "strike_rate": 91.20, "powerplay_sr": 105, "middle_sr": 88, "death_sr": 90, "vs_pace": 0.82, "vs_spin": 0.78, "pressure_factor": 0.82}, "bowling": {"economy": 4.78, "wickets_per_over": 0.06, "dot_ball_pct": 0.38}, "era": "1989-2011"},
    {"id": "aravinda_desilva", "name": "Aravinda de Silva", "country": "Sri Lanka", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 34.90, "strike_rate": 81.13, "powerplay_sr": 75, "middle_sr": 82, "death_sr": 90, "vs_pace": 0.85, "vs_spin": 0.88, "pressure_factor": 0.90}, "bowling": {"economy": 5.20, "wickets_per_over": 0.03, "dot_ball_pct": 0.28}, "era": "1984-2003"},
    {"id": "kumar_sangakkara", "name": "Kumar Sangakkara", "country": "Sri Lanka", "role": "Wicketkeeper-Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm off break", "batting": {"average": 41.98, "strike_rate": 78.86, "powerplay_sr": 72, "middle_sr": 80, "death_sr": 85, "vs_pace": 0.88, "vs_spin": 0.90, "pressure_factor": 0.92}, "bowling": {"economy": 6.00, "wickets_per_over": 0.01, "dot_ball_pct": 0.20}, "era": "2000-2015"},
    {"id": "mahela_jayawardene", "name": "Mahela Jayawardene", "country": "Sri Lanka", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 33.37, "strike_rate": 78.96, "powerplay_sr": 70, "middle_sr": 80, "death_sr": 88, "vs_pace": 0.85, "vs_spin": 0.90, "pressure_factor": 0.88}, "bowling": {"economy": 5.80, "wickets_per_over": 0.02, "dot_ball_pct": 0.25}, "era": "1998-2015"},
    {"id": "tillakaratne_dilshan", "name": "Tillakaratne Dilshan", "country": "Sri Lanka", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 39.26, "strike_rate": 86.00, "powerplay_sr": 95, "middle_sr": 85, "death_sr": 88, "vs_pace": 0.85, "vs_spin": 0.82, "pressure_factor": 0.85}, "bowling": {"economy": 5.35, "wickets_per_over": 0.04, "dot_ball_pct": 0.30}, "era": "1999-2016"},
    
    # New Zealand
    {"id": "martin_crowe", "name": "Martin Crowe", "country": "New Zealand", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 38.55, "strike_rate": 66.99, "powerplay_sr": 62, "middle_sr": 68, "death_sr": 72, "vs_pace": 0.85, "vs_spin": 0.88, "pressure_factor": 0.90}, "bowling": {"economy": 4.98, "wickets_per_over": 0.04, "dot_ball_pct": 0.32}, "era": "1982-1995"},
    {"id": "kane_williamson", "name": "Kane Williamson", "country": "New Zealand", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 47.48, "strike_rate": 81.79, "powerplay_sr": 72, "middle_sr": 82, "death_sr": 92, "vs_pace": 0.90, "vs_spin": 0.88, "pressure_factor": 0.92}, "bowling": {"economy": 5.50, "wickets_per_over": 0.03, "dot_ball_pct": 0.28}, "era": "2010-present"},
    {"id": "ross_taylor", "name": "Ross Taylor", "country": "New Zealand", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 48.20, "strike_rate": 83.48, "powerplay_sr": 75, "middle_sr": 85, "death_sr": 92, "vs_pace": 0.85, "vs_spin": 0.88, "pressure_factor": 0.88}, "bowling": {"economy": 5.80, "wickets_per_over": 0.02, "dot_ball_pct": 0.25}, "era": "2006-2022"},
    {"id": "brendon_mccullum", "name": "Brendon McCullum", "country": "New Zealand", "role": "Wicketkeeper-Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 30.41, "strike_rate": 96.37, "powerplay_sr": 105, "middle_sr": 95, "death_sr": 100, "vs_pace": 0.82, "vs_spin": 0.78, "pressure_factor": 0.85}, "bowling": {"economy": 0, "wickets_per_over": 0, "dot_ball_pct": 0}, "era": "2002-2016"},
    {"id": "stephen_fleming", "name": "Stephen Fleming", "country": "New Zealand", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm off break", "batting": {"average": 32.40, "strike_rate": 71.35, "powerplay_sr": 68, "middle_sr": 72, "death_sr": 78, "vs_pace": 0.85, "vs_spin": 0.82, "pressure_factor": 0.88}, "bowling": {"economy": 5.80, "wickets_per_over": 0.02, "dot_ball_pct": 0.25}, "era": "1994-2007"},
    
    # ============ BOWLERS ============
    # Fast Bowlers
    {"id": "wasim_akram", "name": "Wasim Akram", "country": "Pakistan", "role": "Bowler", "batting_style": "Left-handed", "bowling_style": "Left-arm fast", "batting": {"average": 16.52, "strike_rate": 87.00, "powerplay_sr": 80, "middle_sr": 85, "death_sr": 100, "vs_pace": 0.65, "vs_spin": 0.70, "pressure_factor": 0.75}, "bowling": {"economy": 3.89, "wickets_per_over": 0.10, "dot_ball_pct": 0.48, "powerplay_eff": 0.92, "death_eff": 0.88, "swing": 0.95, "seam": 0.85, "pace": 145}, "era": "1984-2003"},
    {"id": "waqar_younis", "name": "Waqar Younis", "country": "Pakistan", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 10.36, "strike_rate": 75.00, "powerplay_sr": 70, "middle_sr": 75, "death_sr": 85, "vs_pace": 0.60, "vs_spin": 0.65, "pressure_factor": 0.70}, "bowling": {"economy": 4.68, "wickets_per_over": 0.10, "dot_ball_pct": 0.45, "powerplay_eff": 0.88, "death_eff": 0.95, "swing": 0.88, "seam": 0.90, "pace": 148}, "era": "1989-2003"},
    {"id": "shoaib_akhtar", "name": "Shoaib Akhtar", "country": "Pakistan", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 7.90, "strike_rate": 65.00, "powerplay_sr": 60, "middle_sr": 65, "death_sr": 75, "vs_pace": 0.55, "vs_spin": 0.60, "pressure_factor": 0.65}, "bowling": {"economy": 4.77, "wickets_per_over": 0.09, "dot_ball_pct": 0.42, "powerplay_eff": 0.92, "death_eff": 0.85, "swing": 0.80, "seam": 0.85, "pace": 160}, "era": "1998-2011"},
    {"id": "glenn_mcgrath", "name": "Glenn McGrath", "country": "Australia", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 3.40, "strike_rate": 35.00, "powerplay_sr": 30, "middle_sr": 35, "death_sr": 45, "vs_pace": 0.45, "vs_spin": 0.50, "pressure_factor": 0.55}, "bowling": {"economy": 3.88, "wickets_per_over": 0.09, "dot_ball_pct": 0.50, "powerplay_eff": 0.95, "death_eff": 0.85, "swing": 0.75, "seam": 0.95, "pace": 140}, "era": "1993-2007"},
    {"id": "brett_lee", "name": "Brett Lee", "country": "Australia", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 13.00, "strike_rate": 90.00, "powerplay_sr": 85, "middle_sr": 90, "death_sr": 100, "vs_pace": 0.62, "vs_spin": 0.65, "pressure_factor": 0.68}, "bowling": {"economy": 4.76, "wickets_per_over": 0.09, "dot_ball_pct": 0.45, "powerplay_eff": 0.90, "death_eff": 0.92, "swing": 0.82, "seam": 0.85, "pace": 155}, "era": "1999-2012"},
    {"id": "mitchell_starc", "name": "Mitchell Starc", "country": "Australia", "role": "Bowler", "batting_style": "Left-handed", "bowling_style": "Left-arm fast", "batting": {"average": 11.00, "strike_rate": 85.00, "powerplay_sr": 80, "middle_sr": 85, "death_sr": 95, "vs_pace": 0.58, "vs_spin": 0.62, "pressure_factor": 0.65}, "bowling": {"economy": 5.02, "wickets_per_over": 0.10, "dot_ball_pct": 0.44, "powerplay_eff": 0.95, "death_eff": 0.90, "swing": 0.92, "seam": 0.85, "pace": 150}, "era": "2010-present"},
    {"id": "pat_cummins", "name": "Pat Cummins", "country": "Australia", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 15.50, "strike_rate": 80.00, "powerplay_sr": 75, "middle_sr": 80, "death_sr": 90, "vs_pace": 0.60, "vs_spin": 0.65, "pressure_factor": 0.68}, "bowling": {"economy": 5.25, "wickets_per_over": 0.09, "dot_ball_pct": 0.42, "powerplay_eff": 0.88, "death_eff": 0.88, "swing": 0.78, "seam": 0.88, "pace": 145}, "era": "2011-present"},
    {"id": "jasprit_bumrah", "name": "Jasprit Bumrah", "country": "India", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 5.00, "strike_rate": 60.00, "powerplay_sr": 55, "middle_sr": 60, "death_sr": 70, "vs_pace": 0.50, "vs_spin": 0.55, "pressure_factor": 0.58}, "bowling": {"economy": 4.63, "wickets_per_over": 0.10, "dot_ball_pct": 0.48, "powerplay_eff": 0.92, "death_eff": 0.98, "swing": 0.80, "seam": 0.85, "pace": 145}, "era": "2016-present"},
    {"id": "javagal_srinath", "name": "Javagal Srinath", "country": "India", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 8.50, "strike_rate": 65.00, "powerplay_sr": 60, "middle_sr": 65, "death_sr": 75, "vs_pace": 0.55, "vs_spin": 0.60, "pressure_factor": 0.62}, "bowling": {"economy": 4.44, "wickets_per_over": 0.08, "dot_ball_pct": 0.45, "powerplay_eff": 0.88, "death_eff": 0.82, "swing": 0.85, "seam": 0.88, "pace": 142}, "era": "1991-2003"},
    {"id": "zaheer_khan", "name": "Zaheer Khan", "country": "India", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Left-arm fast-medium", "batting": {"average": 11.50, "strike_rate": 75.00, "powerplay_sr": 70, "middle_sr": 75, "death_sr": 85, "vs_pace": 0.58, "vs_spin": 0.62, "pressure_factor": 0.65}, "bowling": {"economy": 4.95, "wickets_per_over": 0.08, "dot_ball_pct": 0.42, "powerplay_eff": 0.90, "death_eff": 0.85, "swing": 0.92, "seam": 0.82, "pace": 138}, "era": "2000-2014"},
    {"id": "mohammed_shami", "name": "Mohammed Shami", "country": "India", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 6.00, "strike_rate": 55.00, "powerplay_sr": 50, "middle_sr": 55, "death_sr": 65, "vs_pace": 0.48, "vs_spin": 0.52, "pressure_factor": 0.55}, "bowling": {"economy": 5.42, "wickets_per_over": 0.09, "dot_ball_pct": 0.40, "powerplay_eff": 0.88, "death_eff": 0.85, "swing": 0.88, "seam": 0.90, "pace": 142}, "era": "2013-present"},
    {"id": "dale_steyn", "name": "Dale Steyn", "country": "South Africa", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 9.50, "strike_rate": 70.00, "powerplay_sr": 65, "middle_sr": 70, "death_sr": 80, "vs_pace": 0.55, "vs_spin": 0.60, "pressure_factor": 0.62}, "bowling": {"economy": 4.87, "wickets_per_over": 0.09, "dot_ball_pct": 0.45, "powerplay_eff": 0.95, "death_eff": 0.85, "swing": 0.90, "seam": 0.92, "pace": 150}, "era": "2004-2019"},
    {"id": "shaun_pollock", "name": "Shaun Pollock", "country": "South Africa", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 26.45, "strike_rate": 73.50, "powerplay_sr": 68, "middle_sr": 72, "death_sr": 85, "vs_pace": 0.72, "vs_spin": 0.75, "pressure_factor": 0.78}, "bowling": {"economy": 3.67, "wickets_per_over": 0.09, "dot_ball_pct": 0.52, "powerplay_eff": 0.92, "death_eff": 0.88, "swing": 0.85, "seam": 0.90, "pace": 138}, "era": "1996-2008"},
    {"id": "allan_donald", "name": "Allan Donald", "country": "South Africa", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 6.20, "strike_rate": 55.00, "powerplay_sr": 50, "middle_sr": 55, "death_sr": 65, "vs_pace": 0.48, "vs_spin": 0.52, "pressure_factor": 0.55}, "bowling": {"economy": 4.14, "wickets_per_over": 0.09, "dot_ball_pct": 0.48, "powerplay_eff": 0.92, "death_eff": 0.85, "swing": 0.82, "seam": 0.90, "pace": 150}, "era": "1991-2003"},
    {"id": "curtly_ambrose", "name": "Curtly Ambrose", "country": "West Indies", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 5.00, "strike_rate": 45.00, "powerplay_sr": 40, "middle_sr": 45, "death_sr": 55, "vs_pace": 0.42, "vs_spin": 0.48, "pressure_factor": 0.50}, "bowling": {"economy": 3.48, "wickets_per_over": 0.09, "dot_ball_pct": 0.55, "powerplay_eff": 0.95, "death_eff": 0.82, "swing": 0.78, "seam": 0.95, "pace": 148}, "era": "1988-2000"},
    {"id": "courtney_walsh", "name": "Courtney Walsh", "country": "West Indies", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 4.50, "strike_rate": 40.00, "powerplay_sr": 35, "middle_sr": 40, "death_sr": 50, "vs_pace": 0.38, "vs_spin": 0.42, "pressure_factor": 0.45}, "bowling": {"economy": 3.95, "wickets_per_over": 0.08, "dot_ball_pct": 0.50, "powerplay_eff": 0.90, "death_eff": 0.80, "swing": 0.75, "seam": 0.88, "pace": 145}, "era": "1984-2001"},
    {"id": "malcolm_marshall", "name": "Malcolm Marshall", "country": "West Indies", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 14.50, "strike_rate": 75.00, "powerplay_sr": 70, "middle_sr": 75, "death_sr": 85, "vs_pace": 0.60, "vs_spin": 0.65, "pressure_factor": 0.68}, "bowling": {"economy": 3.53, "wickets_per_over": 0.10, "dot_ball_pct": 0.52, "powerplay_eff": 0.95, "death_eff": 0.88, "swing": 0.90, "seam": 0.92, "pace": 148}, "era": "1980-1992"},
    {"id": "james_anderson", "name": "James Anderson", "country": "England", "role": "Bowler", "batting_style": "Left-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 8.00, "strike_rate": 60.00, "powerplay_sr": 55, "middle_sr": 60, "death_sr": 70, "vs_pace": 0.52, "vs_spin": 0.58, "pressure_factor": 0.60}, "bowling": {"economy": 4.92, "wickets_per_over": 0.08, "dot_ball_pct": 0.42, "powerplay_eff": 0.90, "death_eff": 0.78, "swing": 0.98, "seam": 0.85, "pace": 138}, "era": "2002-present"},
    {"id": "stuart_broad", "name": "Stuart Broad", "country": "England", "role": "Bowler", "batting_style": "Left-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 10.50, "strike_rate": 70.00, "powerplay_sr": 65, "middle_sr": 70, "death_sr": 80, "vs_pace": 0.55, "vs_spin": 0.60, "pressure_factor": 0.62}, "bowling": {"economy": 5.25, "wickets_per_over": 0.08, "dot_ball_pct": 0.40, "powerplay_eff": 0.85, "death_eff": 0.78, "swing": 0.85, "seam": 0.88, "pace": 140}, "era": "2006-2023"},
    {"id": "lasith_malinga", "name": "Lasith Malinga", "country": "Sri Lanka", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 6.50, "strike_rate": 65.00, "powerplay_sr": 60, "middle_sr": 65, "death_sr": 75, "vs_pace": 0.50, "vs_spin": 0.55, "pressure_factor": 0.58}, "bowling": {"economy": 5.26, "wickets_per_over": 0.10, "dot_ball_pct": 0.42, "powerplay_eff": 0.85, "death_eff": 0.98, "swing": 0.72, "seam": 0.78, "pace": 148}, "era": "2004-2019"},
    {"id": "chaminda_vaas", "name": "Chaminda Vaas", "country": "Sri Lanka", "role": "Bowler", "batting_style": "Left-handed", "bowling_style": "Left-arm medium-fast", "batting": {"average": 11.40, "strike_rate": 70.00, "powerplay_sr": 65, "middle_sr": 70, "death_sr": 80, "vs_pace": 0.58, "vs_spin": 0.62, "pressure_factor": 0.65}, "bowling": {"economy": 4.18, "wickets_per_over": 0.08, "dot_ball_pct": 0.48, "powerplay_eff": 0.92, "death_eff": 0.82, "swing": 0.92, "seam": 0.85, "pace": 135}, "era": "1994-2008"},
    {"id": "trent_boult", "name": "Trent Boult", "country": "New Zealand", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Left-arm fast", "batting": {"average": 4.50, "strike_rate": 50.00, "powerplay_sr": 45, "middle_sr": 50, "death_sr": 60, "vs_pace": 0.42, "vs_spin": 0.48, "pressure_factor": 0.50}, "bowling": {"economy": 4.97, "wickets_per_over": 0.09, "dot_ball_pct": 0.44, "powerplay_eff": 0.95, "death_eff": 0.85, "swing": 0.95, "seam": 0.85, "pace": 140}, "era": "2012-present"},
    {"id": "tim_southee", "name": "Tim Southee", "country": "New Zealand", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 12.50, "strike_rate": 80.00, "powerplay_sr": 75, "middle_sr": 80, "death_sr": 90, "vs_pace": 0.58, "vs_spin": 0.62, "pressure_factor": 0.65}, "bowling": {"economy": 5.38, "wickets_per_over": 0.08, "dot_ball_pct": 0.40, "powerplay_eff": 0.88, "death_eff": 0.82, "swing": 0.88, "seam": 0.85, "pace": 138}, "era": "2008-present"},
    
    # Spinners
    {"id": "muttiah_muralitharan", "name": "Muttiah Muralitharan", "country": "Sri Lanka", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 6.80, "strike_rate": 55.00, "powerplay_sr": 50, "middle_sr": 55, "death_sr": 65, "vs_pace": 0.48, "vs_spin": 0.52, "pressure_factor": 0.55}, "bowling": {"economy": 3.93, "wickets_per_over": 0.10, "dot_ball_pct": 0.52, "powerplay_eff": 0.78, "death_eff": 0.80, "spin_turn": 0.98, "flight": 0.90, "arm_ball": 0.85}, "era": "1993-2011"},
    {"id": "shane_warne", "name": "Shane Warne", "country": "Australia", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 13.50, "strike_rate": 75.00, "powerplay_sr": 70, "middle_sr": 75, "death_sr": 85, "vs_pace": 0.60, "vs_spin": 0.55, "pressure_factor": 0.62}, "bowling": {"economy": 4.25, "wickets_per_over": 0.09, "dot_ball_pct": 0.48, "powerplay_eff": 0.82, "death_eff": 0.78, "spin_turn": 0.95, "flight": 0.95, "googly": 0.92}, "era": "1993-2005"},
    {"id": "anil_kumble", "name": "Anil Kumble", "country": "India", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 10.50, "strike_rate": 65.00, "powerplay_sr": 60, "middle_sr": 65, "death_sr": 75, "vs_pace": 0.55, "vs_spin": 0.58, "pressure_factor": 0.60}, "bowling": {"economy": 4.30, "wickets_per_over": 0.08, "dot_ball_pct": 0.45, "powerplay_eff": 0.80, "death_eff": 0.75, "spin_turn": 0.82, "flight": 0.78, "flipper": 0.88}, "era": "1990-2007"},
    {"id": "harbhajan_singh", "name": "Harbhajan Singh", "country": "India", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 11.20, "strike_rate": 70.00, "powerplay_sr": 65, "middle_sr": 70, "death_sr": 80, "vs_pace": 0.55, "vs_spin": 0.52, "pressure_factor": 0.58}, "bowling": {"economy": 4.29, "wickets_per_over": 0.07, "dot_ball_pct": 0.45, "powerplay_eff": 0.82, "death_eff": 0.75, "spin_turn": 0.88, "flight": 0.82, "doosra": 0.85}, "era": "1998-2015"},
    {"id": "ravichandran_ashwin", "name": "Ravichandran Ashwin", "country": "India", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 16.50, "strike_rate": 80.00, "powerplay_sr": 75, "middle_sr": 80, "death_sr": 90, "vs_pace": 0.62, "vs_spin": 0.58, "pressure_factor": 0.65}, "bowling": {"economy": 4.91, "wickets_per_over": 0.07, "dot_ball_pct": 0.42, "powerplay_eff": 0.85, "death_eff": 0.78, "spin_turn": 0.90, "flight": 0.85, "carrom_ball": 0.92}, "era": "2010-present"},
    {"id": "ravindra_jadeja", "name": "Ravindra Jadeja", "country": "India", "role": "All-rounder", "batting_style": "Left-handed", "bowling_style": "Left-arm orthodox", "batting": {"average": 32.50, "strike_rate": 88.00, "powerplay_sr": 78, "middle_sr": 85, "death_sr": 105, "vs_pace": 0.75, "vs_spin": 0.72, "pressure_factor": 0.78}, "bowling": {"economy": 4.89, "wickets_per_over": 0.07, "dot_ball_pct": 0.44, "powerplay_eff": 0.82, "death_eff": 0.80, "spin_turn": 0.85, "flight": 0.78, "arm_ball": 0.82}, "era": "2009-present"},
    {"id": "kuldeep_yadav", "name": "Kuldeep Yadav", "country": "India", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Left-arm chinaman", "batting": {"average": 8.00, "strike_rate": 55.00, "powerplay_sr": 50, "middle_sr": 55, "death_sr": 65, "vs_pace": 0.48, "vs_spin": 0.52, "pressure_factor": 0.55}, "bowling": {"economy": 5.05, "wickets_per_over": 0.08, "dot_ball_pct": 0.42, "powerplay_eff": 0.88, "death_eff": 0.78, "spin_turn": 0.92, "flight": 0.88, "googly": 0.95}, "era": "2017-present"},
    {"id": "saqlain_mushtaq", "name": "Saqlain Mushtaq", "country": "Pakistan", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 8.50, "strike_rate": 60.00, "powerplay_sr": 55, "middle_sr": 60, "death_sr": 70, "vs_pace": 0.52, "vs_spin": 0.55, "pressure_factor": 0.58}, "bowling": {"economy": 4.29, "wickets_per_over": 0.09, "dot_ball_pct": 0.48, "powerplay_eff": 0.85, "death_eff": 0.82, "spin_turn": 0.90, "flight": 0.85, "doosra": 0.95}, "era": "1995-2004"},
    {"id": "shahid_afridi", "name": "Shahid Afridi", "country": "Pakistan", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 23.57, "strike_rate": 117.00, "powerplay_sr": 125, "middle_sr": 115, "death_sr": 130, "vs_pace": 0.72, "vs_spin": 0.68, "pressure_factor": 0.70}, "bowling": {"economy": 4.62, "wickets_per_over": 0.08, "dot_ball_pct": 0.42, "powerplay_eff": 0.85, "death_eff": 0.80, "spin_turn": 0.78, "flight": 0.75, "googly": 0.82}, "era": "1996-2018"},
    {"id": "daniel_vettori", "name": "Daniel Vettori", "country": "New Zealand", "role": "All-rounder", "batting_style": "Left-handed", "bowling_style": "Left-arm orthodox", "batting": {"average": 17.50, "strike_rate": 68.00, "powerplay_sr": 62, "middle_sr": 68, "death_sr": 78, "vs_pace": 0.62, "vs_spin": 0.65, "pressure_factor": 0.68}, "bowling": {"economy": 4.18, "wickets_per_over": 0.07, "dot_ball_pct": 0.48, "powerplay_eff": 0.82, "death_eff": 0.80, "spin_turn": 0.85, "flight": 0.88, "arm_ball": 0.82}, "era": "1997-2015"},
    {"id": "imran_tahir", "name": "Imran Tahir", "country": "South Africa", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 5.50, "strike_rate": 50.00, "powerplay_sr": 45, "middle_sr": 50, "death_sr": 60, "vs_pace": 0.42, "vs_spin": 0.48, "pressure_factor": 0.50}, "bowling": {"economy": 4.65, "wickets_per_over": 0.09, "dot_ball_pct": 0.45, "powerplay_eff": 0.88, "death_eff": 0.82, "spin_turn": 0.88, "flight": 0.85, "googly": 0.92}, "era": "2011-2019"},
    {"id": "adil_rashid", "name": "Adil Rashid", "country": "England", "role": "Bowler", "batting_style": "Right-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 12.00, "strike_rate": 75.00, "powerplay_sr": 70, "middle_sr": 75, "death_sr": 85, "vs_pace": 0.55, "vs_spin": 0.52, "pressure_factor": 0.58}, "bowling": {"economy": 5.68, "wickets_per_over": 0.07, "dot_ball_pct": 0.38, "powerplay_eff": 0.82, "death_eff": 0.75, "spin_turn": 0.85, "flight": 0.88, "googly": 0.90}, "era": "2009-present"},
    
    # All-rounders (additional)
    {"id": "kapil_dev", "name": "Kapil Dev", "country": "India", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 23.79, "strike_rate": 95.07, "powerplay_sr": 88, "middle_sr": 95, "death_sr": 110, "vs_pace": 0.78, "vs_spin": 0.75, "pressure_factor": 0.85}, "bowling": {"economy": 3.71, "wickets_per_over": 0.08, "dot_ball_pct": 0.48, "powerplay_eff": 0.90, "death_eff": 0.82, "swing": 0.88, "seam": 0.85, "pace": 138}, "era": "1978-1994"},
    {"id": "imran_khan", "name": "Imran Khan", "country": "Pakistan", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 33.41, "strike_rate": 72.67, "powerplay_sr": 65, "middle_sr": 72, "death_sr": 85, "vs_pace": 0.80, "vs_spin": 0.82, "pressure_factor": 0.92}, "bowling": {"economy": 3.89, "wickets_per_over": 0.08, "dot_ball_pct": 0.50, "powerplay_eff": 0.92, "death_eff": 0.85, "swing": 0.90, "seam": 0.88, "pace": 145}, "era": "1974-1992"},
    {"id": "richard_hadlee", "name": "Richard Hadlee", "country": "New Zealand", "role": "All-rounder", "batting_style": "Left-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 21.56, "strike_rate": 70.00, "powerplay_sr": 65, "middle_sr": 70, "death_sr": 80, "vs_pace": 0.72, "vs_spin": 0.75, "pressure_factor": 0.78}, "bowling": {"economy": 3.30, "wickets_per_over": 0.09, "dot_ball_pct": 0.55, "powerplay_eff": 0.95, "death_eff": 0.82, "swing": 0.95, "seam": 0.90, "pace": 138}, "era": "1973-1990"},
    {"id": "ian_botham", "name": "Ian Botham", "country": "England", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 23.21, "strike_rate": 79.00, "powerplay_sr": 75, "middle_sr": 78, "death_sr": 90, "vs_pace": 0.75, "vs_spin": 0.72, "pressure_factor": 0.80}, "bowling": {"economy": 3.96, "wickets_per_over": 0.07, "dot_ball_pct": 0.48, "powerplay_eff": 0.88, "death_eff": 0.78, "swing": 0.85, "seam": 0.82, "pace": 135}, "era": "1976-1992"},
    {"id": "andrew_flintoff", "name": "Andrew Flintoff", "country": "England", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 32.01, "strike_rate": 87.34, "powerplay_sr": 80, "middle_sr": 88, "death_sr": 100, "vs_pace": 0.78, "vs_spin": 0.75, "pressure_factor": 0.82}, "bowling": {"economy": 4.50, "wickets_per_over": 0.07, "dot_ball_pct": 0.42, "powerplay_eff": 0.88, "death_eff": 0.82, "swing": 0.82, "seam": 0.85, "pace": 145}, "era": "1998-2009"},
    {"id": "lance_klusener", "name": "Lance Klusener", "country": "South Africa", "role": "All-rounder", "batting_style": "Left-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 41.10, "strike_rate": 89.90, "powerplay_sr": 82, "middle_sr": 88, "death_sr": 110, "vs_pace": 0.82, "vs_spin": 0.78, "pressure_factor": 0.85}, "bowling": {"economy": 4.94, "wickets_per_over": 0.07, "dot_ball_pct": 0.40, "powerplay_eff": 0.85, "death_eff": 0.80, "swing": 0.78, "seam": 0.82, "pace": 135}, "era": "1996-2004"},
    {"id": "chris_cairns", "name": "Chris Cairns", "country": "New Zealand", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 29.46, "strike_rate": 81.52, "powerplay_sr": 75, "middle_sr": 80, "death_sr": 95, "vs_pace": 0.75, "vs_spin": 0.72, "pressure_factor": 0.78}, "bowling": {"economy": 4.55, "wickets_per_over": 0.07, "dot_ball_pct": 0.42, "powerplay_eff": 0.85, "death_eff": 0.80, "swing": 0.80, "seam": 0.85, "pace": 140}, "era": "1991-2006"},
    {"id": "hardik_pandya", "name": "Hardik Pandya", "country": "India", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm fast-medium", "batting": {"average": 31.50, "strike_rate": 116.43, "powerplay_sr": 105, "middle_sr": 112, "death_sr": 145, "vs_pace": 0.78, "vs_spin": 0.75, "pressure_factor": 0.80}, "bowling": {"economy": 5.78, "wickets_per_over": 0.06, "dot_ball_pct": 0.38, "powerplay_eff": 0.78, "death_eff": 0.82, "swing": 0.72, "seam": 0.78, "pace": 140}, "era": "2016-present"},
    
    # Additional Players to reach 100
    {"id": "kieron_pollard", "name": "Kieron Pollard", "country": "West Indies", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm medium", "batting": {"average": 26.63, "strike_rate": 99.28, "powerplay_sr": 90, "middle_sr": 95, "death_sr": 130, "vs_pace": 0.75, "vs_spin": 0.72, "pressure_factor": 0.78}, "bowling": {"economy": 5.52, "wickets_per_over": 0.05, "dot_ball_pct": 0.35, "powerplay_eff": 0.72, "death_eff": 0.75, "swing": 0.65, "seam": 0.70, "pace": 130}, "era": "2007-2022"},
    {"id": "dwayne_bravo", "name": "Dwayne Bravo", "country": "West Indies", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm medium-fast", "batting": {"average": 25.50, "strike_rate": 85.00, "powerplay_sr": 78, "middle_sr": 85, "death_sr": 100, "vs_pace": 0.72, "vs_spin": 0.70, "pressure_factor": 0.75}, "bowling": {"economy": 5.23, "wickets_per_over": 0.07, "dot_ball_pct": 0.38, "powerplay_eff": 0.80, "death_eff": 0.90, "swing": 0.70, "seam": 0.75, "pace": 132}, "era": "2004-2019"},
    {"id": "andre_russell", "name": "Andre Russell", "country": "West Indies", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm fast", "batting": {"average": 28.00, "strike_rate": 130.00, "powerplay_sr": 110, "middle_sr": 125, "death_sr": 165, "vs_pace": 0.78, "vs_spin": 0.72, "pressure_factor": 0.75}, "bowling": {"economy": 5.85, "wickets_per_over": 0.06, "dot_ball_pct": 0.35, "powerplay_eff": 0.78, "death_eff": 0.82, "swing": 0.68, "seam": 0.75, "pace": 145}, "era": "2011-present"},
    {"id": "suresh_raina", "name": "Suresh Raina", "country": "India", "role": "Batsman", "batting_style": "Left-handed", "bowling_style": "Right-arm off break", "batting": {"average": 35.31, "strike_rate": 93.50, "powerplay_sr": 85, "middle_sr": 95, "death_sr": 110, "vs_pace": 0.80, "vs_spin": 0.72, "pressure_factor": 0.82}, "bowling": {"economy": 5.50, "wickets_per_over": 0.04, "dot_ball_pct": 0.30, "powerplay_eff": 0.75, "death_eff": 0.70}, "era": "2005-2018"},
    {"id": "virender_sehwag", "name": "Virender Sehwag", "country": "India", "role": "Batsman", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 35.05, "strike_rate": 104.33, "powerplay_sr": 115, "middle_sr": 100, "death_sr": 105, "vs_pace": 0.85, "vs_spin": 0.78, "pressure_factor": 0.80}, "bowling": {"economy": 5.35, "wickets_per_over": 0.03, "dot_ball_pct": 0.28}, "era": "1999-2013"},
    {"id": "mohammad_hafeez", "name": "Mohammad Hafeez", "country": "Pakistan", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 33.64, "strike_rate": 79.85, "powerplay_sr": 85, "middle_sr": 78, "death_sr": 82, "vs_pace": 0.78, "vs_spin": 0.75, "pressure_factor": 0.78}, "bowling": {"economy": 4.60, "wickets_per_over": 0.05, "dot_ball_pct": 0.38, "powerplay_eff": 0.85, "death_eff": 0.75, "spin_turn": 0.72, "flight": 0.70}, "era": "2003-2021"},
    {"id": "marlon_samuels", "name": "Marlon Samuels", "country": "West Indies", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 32.88, "strike_rate": 76.05, "powerplay_sr": 70, "middle_sr": 78, "death_sr": 85, "vs_pace": 0.75, "vs_spin": 0.78, "pressure_factor": 0.82}, "bowling": {"economy": 4.90, "wickets_per_over": 0.04, "dot_ball_pct": 0.35, "powerplay_eff": 0.78, "death_eff": 0.72}, "era": "2000-2018"},
    {"id": "angelo_mathews", "name": "Angelo Mathews", "country": "Sri Lanka", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm medium-fast", "batting": {"average": 42.56, "strike_rate": 79.75, "powerplay_sr": 72, "middle_sr": 80, "death_sr": 92, "vs_pace": 0.80, "vs_spin": 0.82, "pressure_factor": 0.85}, "bowling": {"economy": 5.25, "wickets_per_over": 0.05, "dot_ball_pct": 0.38, "powerplay_eff": 0.78, "death_eff": 0.78, "swing": 0.75, "seam": 0.78, "pace": 130}, "era": "2008-present"},
    {"id": "mohammad_nabi", "name": "Mohammad Nabi", "country": "Afghanistan", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm off break", "batting": {"average": 24.50, "strike_rate": 88.00, "powerplay_sr": 80, "middle_sr": 88, "death_sr": 102, "vs_pace": 0.72, "vs_spin": 0.70, "pressure_factor": 0.75}, "bowling": {"economy": 4.35, "wickets_per_over": 0.06, "dot_ball_pct": 0.42, "powerplay_eff": 0.85, "death_eff": 0.80, "spin_turn": 0.78, "flight": 0.75}, "era": "2009-present"},
    {"id": "rashid_khan", "name": "Rashid Khan", "country": "Afghanistan", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm leg break", "batting": {"average": 18.50, "strike_rate": 135.00, "powerplay_sr": 120, "middle_sr": 130, "death_sr": 160, "vs_pace": 0.68, "vs_spin": 0.65, "pressure_factor": 0.70}, "bowling": {"economy": 4.18, "wickets_per_over": 0.09, "dot_ball_pct": 0.48, "powerplay_eff": 0.90, "death_eff": 0.85, "spin_turn": 0.92, "flight": 0.82, "googly": 0.95}, "era": "2015-present"},
    {"id": "mitchell_johnson", "name": "Mitchell Johnson", "country": "Australia", "role": "Bowler", "batting_style": "Left-handed", "bowling_style": "Left-arm fast", "batting": {"average": 14.50, "strike_rate": 85.00, "powerplay_sr": 80, "middle_sr": 85, "death_sr": 95, "vs_pace": 0.60, "vs_spin": 0.62, "pressure_factor": 0.65}, "bowling": {"economy": 4.95, "wickets_per_over": 0.08, "dot_ball_pct": 0.42, "powerplay_eff": 0.88, "death_eff": 0.85, "swing": 0.85, "seam": 0.82, "pace": 152}, "era": "2005-2015"},
    {"id": "jason_holder", "name": "Jason Holder", "country": "West Indies", "role": "All-rounder", "batting_style": "Right-handed", "bowling_style": "Right-arm medium-fast", "batting": {"average": 23.50, "strike_rate": 82.00, "powerplay_sr": 75, "middle_sr": 82, "death_sr": 95, "vs_pace": 0.72, "vs_spin": 0.70, "pressure_factor": 0.75}, "bowling": {"economy": 5.20, "wickets_per_over": 0.06, "dot_ball_pct": 0.40, "powerplay_eff": 0.82, "death_eff": 0.80, "swing": 0.78, "seam": 0.80, "pace": 135}, "era": "2013-present"},
]

# Get all players
def get_all_players():
    return PLAYERS_DATA

# Get player by ID
def get_player_by_id(player_id: str):
    for player in PLAYERS_DATA:
        if player["id"] == player_id:
            return player
    return None

# Get players by country
def get_players_by_country(country: str):
    return [p for p in PLAYERS_DATA if p["country"] == country]

# Get players by role
def get_players_by_role(role: str):
    return [p for p in PLAYERS_DATA if p["role"] == role]
